# -*- coding: utf-8 -*-
"""HF_diego_R-loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcEI8LQYn5LiKjl27WsTI2YZdfTtqTgN
"""

#!pip install econml

#!pip install dowhy

#!pip install xgboost

# Importing required libraries
import random
import os
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import expon
import scipy.stats as stats
import statsmodels.api as sm
from dowhy import CausalModel
from dowhy.causal_estimator import CausalEstimate
from sklearn.preprocessing import StandardScaler




# Set seeds for reproducibility
def seed_everything(seed=123):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    os.environ['TF_DETERMINISTIC_OPS'] = '1'

seed = 123
seed_everything(seed)
warnings.filterwarnings('ignore')
pd.set_option('display.float_format', lambda x: '%.2f' % x)

#from google.colab import drive
#drive.mount('/content/drive')

#%%

import pandas as pd

# Adjust the path if your file is in a different directory within your Drive
file_path = 'D:/data_final.csv'
data_all_dengue = pd.read_csv(file_path, encoding='latin1')

#%%

data_all_dengue = data_all_dengue.dropna()

columnas_to_drop = ['Year_month', 'Period', 'cases', 'expected', 'SIR_mean', 'SIR_lwr95', 'SIR_upr95']

# 1. Label Encoding DANE
le = LabelEncoder()
data_all_dengue['DANE_labeled'] = le.fit_transform(data_all_dengue['DANE'])
scaler = MinMaxScaler()
data_all_dengue['DANE_normalized'] = scaler.fit_transform(
    data_all_dengue[['DANE_labeled']]
)

# 2. Label Encoding Deparment_DANE
le_year = LabelEncoder()
data_all_dengue['DANE_year_labeled'] = le_year.fit_transform(data_all_dengue['DANE_year'])
scaler_DDANE = MinMaxScaler()
data_all_dengue['DANE_year_normalized'] = scaler_DDANE.fit_transform(
    data_all_dengue[['DANE_year_labeled']]
)

#3. Label Encoding DANE-Year-Month
le_year_month = LabelEncoder()
data_all_dengue['DANE_period_labeled'] = le_year_month.fit_transform(data_all_dengue['DANE_period'])
scaler_DDANE = MinMaxScaler()
data_all_dengue['DANE_period_normalized'] = scaler_DDANE.fit_transform(
    data_all_dengue[['DANE_period_labeled']]
)

data_all_dengue.drop(columns=columnas_to_drop, inplace=True)

#%%

scaler = StandardScaler()
data_all_dengue['SST12'] = scaler.fit_transform(data_all_dengue[['SST12']])
data_all_dengue['SST3'] = scaler.fit_transform(data_all_dengue[['SST3']])
data_all_dengue['SST34'] = scaler.fit_transform(data_all_dengue[['SST34']])
data_all_dengue['SST4'] = scaler.fit_transform(data_all_dengue[['SST4']])
data_all_dengue['NATL'] = scaler.fit_transform(data_all_dengue[['NATL']])
data_all_dengue['SATL'] = scaler.fit_transform(data_all_dengue[['SATL']])
data_all_dengue['TROP'] = scaler.fit_transform(data_all_dengue[['TROP']])
data_all_dengue['SOI'] = scaler.fit_transform(data_all_dengue[['SOI']])
data_all_dengue['ESOI'] = scaler.fit_transform(data_all_dengue[['ESOI']])
data_all_dengue['cpolr'] = scaler.fit_transform(data_all_dengue[['cpolr']])
data_all_dengue['Zonal_Winds'] = scaler.fit_transform(data_all_dengue[['Zonal_Winds']])
data_all_dengue['epac'] = scaler.fit_transform(data_all_dengue[['epac']])
data_all_dengue['qbo_u30'] = scaler.fit_transform(data_all_dengue[['qbo_u30']])
data_all_dengue['MPI'] = scaler.fit_transform(data_all_dengue[['MPI']])
data_all_dengue['altitude'] = scaler.fit_transform(data_all_dengue[['altitude']])
data_all_dengue['pop_density'] = scaler.fit_transform(data_all_dengue[['pop_density']])
data_all_dengue['rainfall'] = scaler.fit_transform(data_all_dengue[['rainfall']])


data_all_dengue["cosin_month"] = np.cos(2 * np.pi * data_all_dengue["Month"] / 12)
data_all_dengue["sin_month"] = np.sin(2 * np.pi * data_all_dengue["Month"] / 12)

data_all_dengue["Year"] = data_all_dengue["Year"]-2007

# std
data_std_dengue = data_all_dengue

# Ensure correct temporal order
data_std_dengue = data_std_dengue.sort_values(
    by=['DANE_normalized', 'DANE_year_normalized', 'DANE_period_normalized']
).reset_index(drop=True)

data_std_dengue = data_std_dengue.dropna()

data_std_dengue = data_std_dengue[['DANE_normalized', 'DANE_year_normalized', 'DANE_period_normalized',
                     'SST12', 'SST3', 'SST34', 'SST4', 'NATL', 'SATL', 'TROP', 'SOI', 'ESOI', 'cpolr', 'Zonal_Winds', 'epac', 'qbo_u30',                                         
                     'MPI', 'altitude', 'pop_density', 'rainfall',  
                     'episodes',                   
                     'sin_month', 'cosin_month', 'Year',                      
                     'temperature', 'excess']]

#%%

model_dengue = CausalModel(
    data=data_std_dengue,
    treatment=['temperature'],
    outcome=['excess'],
    graph="""
    digraph {

        sin_month -> temperature
        sin_month -> excess
        cosin_month -> temperature
        cosin_month -> excess
        Year -> temperature
        Year -> excess
                
        sin_month -> SST12
        sin_month -> SST3        
        sin_month -> SST34
        sin_month -> SST4
        sin_month -> NATL
        sin_month -> SATL
        sin_month -> TROP
        sin_month -> SOI
        sin_month -> ESOI
        sin_month -> cpolr
        sin_month -> Zonal_Winds
        sin_month -> epac
        sin_month -> qbo_u30
        
        cosin_month -> SST12
        cosin_month -> SST3        
        cosin_month -> SST34
        cosin_month -> SST4
        cosin_month -> NATL
        cosin_month -> SATL
        cosin_month -> TROP
        cosin_month -> SOI
        cosin_month -> ESOI
        cosin_month -> cpolr
        cosin_month -> Zonal_Winds
        cosin_month -> epac
        cosin_month -> qbo_u30
        
        Year -> SST12
        Year -> SST3        
        Year -> SST34
        Year -> SST4
        Year -> NATL
        Year -> SATL
        Year -> TROP
        Year -> SOI
        Year -> ESOI
        Year -> cpolr
        Year -> Zonal_Winds
        Year -> epac
        Year -> qbo_u30        
        
        sin_month -> episodes
        sin_month -> rainfall
        cosin_month -> episodes
        cosin_month -> rainfall
        Year -> episodes
        Year -> rainfall
        
        SST12 -> temperature
        SST3  -> temperature      
        SST34 -> temperature
        SST4 -> temperature
        NATL -> temperature
        SATL -> temperature
        TROP -> temperature
        SOI -> temperature
        ESOI -> temperature
        cpolr -> temperature
        Zonal_Winds -> temperature
        epac -> temperature
        qbo_u30 -> temperature
        
        SST12 -> excess
        SST3  -> excess      
        SST34 -> excess
        SST4 -> excess
        NATL -> excess
        SATL -> excess
        TROP -> excess
        SOI -> excess
        ESOI -> excess
        cpolr -> excess
        Zonal_Winds -> excess
        epac -> excess
        qbo_u30 -> excess
        
        SST12 -> episodes
        SST3  -> episodes      
        SST34 -> episodes
        SST4 -> episodes
        NATL -> episodes
        SATL -> episodes
        TROP -> episodes
        SOI -> episodes
        ESOI -> episodes
        cpolr -> episodes
        Zonal_Winds -> episodes
        epac -> episodes
        qbo_u30 -> episodes
        
        SST12 -> rainfall
        SST3  -> rainfall      
        SST34 -> rainfall
        SST4 -> rainfall
        NATL -> rainfall
        SATL -> rainfall
        TROP -> rainfall
        SOI -> rainfall
        ESOI -> rainfall
        cpolr -> rainfall
        Zonal_Winds -> rainfall
        epac -> rainfall
        qbo_u30 -> rainfall
        
        altitude -> temperature
        altitude -> rainfall
        
        episodes -> temperature
        episodes -> rainfall
        episodes -> excess
        
        temperature -> MPI
        
        rainfall -> temperature
        rainfall -> excess
        rainfall -> MPI
        
        MPI -> excess
        MPI -> pop_density
        
        pop_density -> excess
       
       
        DANE_normalized -> excess
        DANE_year_normalized -> excess
        DANE_period_normalized -> excess
        
        temperature -> excess

    }
    """
)

#%%

# Identifying effects
identified_estimand_dengue = model_dengue.identify_effect(proceed_when_unidentifiable=None)
print(identified_estimand_dengue)

#%%
